services:
  - type: web
    name: crm-crm
    runtime: node
    buildCommand: cd client && npm install && npm run build && cd ../server && node scripts/copyBuild.js && npm install && npm run seed:demo
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
